config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :homes

  resources :products

  resources :users 

  match ':controller(/:action(/:id))', :via => [:get,:post]

  root "homes#index"

  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
belongs_to :user
has_attached_file :image_name, :styles => { :medium => "300x300>", :thumb => "100x100>" }, default_url: "homeDefault.png"
validates_attachment_content_type :image_name, :content_type => /\Aimage\/.*\Z/
#validates :image_name, :attachment_presence => true

#validates_attachment_content_type :image_name, :content_type => /\Aimage/

  # Validate filename
  #validates_attachment_file_name :image_name, :matches => [/png\Z/, /jpe?g\Z/]
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  load_and_authorize_resource 

  before_action :authenticate_user! , :except => [:index,:show]
  before_action :set_product, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @user_asso = current_user
    @product =  @user_asso.products.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @user_asso = current_user
    @product = @user_asso.products.new(product_params)

      if @product.save
        redirect_to @product, notice: 'Product was successfully created.' 
        
      else
       render :new 
       
      end
    end
  

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:ad_title, :rent_type, :prise, :area, 
        :owner_type, :condition, :extra, :image_name)
    end


 end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product,:html=>{:multipart =>false}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table summary="Create New Ad">
    <tr>
    <th><%= f.label(:ad_title, "Title") %></th>
    <td><%= f.text_field(:ad_title) %></td>
  </tr>
  <tr>
    <th><%= f.label(:rent_type) %></th>
    <td><%= f.select :rent_type, [['Rent','Rent'],['Sharing','Sharing']] %></td>
  </tr>
  <tr>
    <th><%= f.label(:prise) %></th>
    <td><%= f.text_field(:prise) %></td>
  </tr>
  <tr>
    <th><%= f.label(:area) %></th>
    <td><%= f.text_field(:area) %></td>
  </tr>
  <tr>
    <th><%= f.label(:owner_type) %></th>
    <td><%= f.select :owner_type, [['Owner','Owner'],['Broker','Broker']] %></td>
  </tr>
  <tr>
    <th><%= f.label(:condition) %></th>
    <td><%= f.select :condition ,[['Furnished','Furnished'],['Semi Furnished','Semi Furnished'],['Empty','Empty']] %></td>
  </tr>
  <tr>
    <th><%= f.label(:extra) %></th>
    <td><%= f.text_field(:extra) %></td>
  </tr>
  <tr>
    <th><%= f.label(:image_name) %></th>
    <td><%= f.file_field(:image_name) %></td>
  </tr>
  
</table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_login_modal.html.erb
<!-- Modal for login -->
<div class="modal fade" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="loginModal">Login</h4>
      </div>
      <div class="modal-body">
			
			  <%= form_tag(:controller => 'acess' , :action => 'attempt_login') do %>
			  <table class="">
			    <tr>
		    <div class="form-group">
			    <%= label_tag(:username) %>
			      <%= text_field_tag(:username) %>
			   
			</div>
			<div class="form-group">
			    
			      <%= label_tag(:password) %>
			      <%= password_field_tag(:password) %>
			    
			</div>
			    <tr>
			      <td>&nbsp;</td>
			      <td></td>
			    </tr>
			  </table>
			 	<div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">close</button>
			        <%= submit_tag 'Login', class: 'btn btn-success' %>
			        
			     </div>
			 <% end %>

      </div>
      

    </div>
  </div>
</div>

<!-- Modal Login finish -->

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
            <%= product.ad_title %>
        </td>

      </tr>
      <tr>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


Ad Title : <%= @product.ad_title%> <br/>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %> |
<%= link_to 'Home', homes_path %>